AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  honeycode-apis

  Sample SAM Template for honeycode-apis

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  getScreenDataAll:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_screen_data/
      Handler: getScreenDataAll.lambda_handler
      Runtime: python3.6
      Timeout: 10
      Policies:
      - AmazonHoneycodeFullAccess
      - AmazonS3FullAccess
      
  createNewItem:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_screen_data/
      Handler: invoke_screen_automation.lambda_handler
      Runtime: python3.6
      Timeout: 10
      Policies:
      - AmazonHoneycodeFullAccess
      - AmazonS3FullAccess
        


